radiko_app/urls.py
from django.urls import path

from . import views

app_name = 'radiko_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('stream/<str:station_id>', views.Tune.as_view(), name='tune'),
    path('station/', views.ListStation.as_view(), name='station'),
    path('mpd/station/', views.ListStationMPD.as_view(), name='station_mpd'),
    path('stream/station/', views.ListStationStream.as_view(), name='station_stream'),
    path('status/', views.MPDStatus.as_view(), name='status'),
    path('program/<str:station_id>', views.ListProgram.as_view(), name='program'),
    path('mpd/program/<str:station_id>', views.ListProgram.as_view(), {'target': 'mpd'}, name='program_mpd'),
    path('stream/program/<str:station_id>', views.ListProgram.as_view(), {'target': 'stream'}, name='program_stream'),
]

radio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('radiko/', include('radiko_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% block title %}radiko app{% endblock %}</title>
</head>
<body>
<div class="container">
    <header>
        <p class="site-name"><a href="{% url 'radiko_app:index' %}">Radiko App</a></p>
        <nav>
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}" class="logout">Logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="login">Login</a>
            {% endif %}            
        </nav>
        <br>
    </header>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>

templates/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="style.css" />
    <title>{% block title %}Radio Relay Server{% endblock %}</title>
</head>

<body>
    <div id="content">
        {% block body %}{% endblock %}
    </div>
</body>
</html>