radiko_app/urls.py
from django.urls import path

from . import views

app_name = 'radiko_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('stream/<str:station_id>', views.Tune.as_view(), name='tune'),
    path('station/', views.ListStation.as_view(), name='station'),
    path('mpd/station/', views.ListStationMPD.as_view(), name='station_mpd'),
    path('stream/station/', views.ListStationStream.as_view(), name='station_stream'),
    path('status/', views.MPDStatus.as_view(), name='status'),
    path('program/<str:station_id>', views.ListProgram.as_view(), name='program'),
    path('mpd/program/<str:station_id>', views.ListProgram.as_view(), {'target': 'mpd'}, name='program_mpd'),
    path('stream/program/<str:station_id>', views.ListProgram.as_view(), {'target': 'stream'}, name='program_stream'),
]

radio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('radiko/', include('radiko_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

radiko_app/models.py
from django.db import models

# Create your models here.

class Station(models.Model):
    station_no = models.IntegerField()
    station_id = models.CharField(max_length=30,primary_key=True)
    name = models.CharField(max_length=100)
    area_id = models.CharField(max_length=4)
    area_name = models.CharField(max_length=30)
    region = models.CharField(max_length=30)

class Program(models.Model):
    id = models.IntegerField(primary_key=True)
    station_id = models.CharField(max_length=30)
    station_name = models.CharField(max_length=100)
    date = models.CharField(max_length=8)
    title = models.CharField(max_length=100)
    failed_record = models.CharField(max_length=1)
    desc = models.CharField(max_length=2000, null=True)
    info = models.CharField(max_length=2000, null=True)
    pfm = models.CharField(max_length=200, null=True)
    prog_id = models.CharField(max_length=10)
    ft = models.CharField(max_length=14)
    to = models.CharField(max_length=14)
    dur = models.CharField(max_length=14)
    download = models.IntegerField()
    
    class Meta:
        unique_together=('station_id', 'prog_id')

radiko_app/views.py
import logging
import subprocess
import re
import json

from django.views import View
from django.http import HttpResponse, StreamingHttpResponse
from django.shortcuts import render, redirect
from django.utils.timezone import datetime, timedelta
from django.core import serializers
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Station, Program
from . import radiko
from .tasks import download_program, record_program

from mpd import MPDClient

def index(request):
    return redirect('station/')

def mpd_play(content, title):
        client = MPDClient()
        client.connect(settings.MPD_ADDR, settings.MPD_PORT)
        client.clear()
        plid = client.addid(content)
        client.addtagid(plid, 'Title', title)
        client.playid(plid)

def mpd_status():
    client = MPDClient()
    client.connect(settings.MPD_ADDR, settings.MPD_PORT)
    status = client.status()
    current = client.currentsong()
    if 'elapsed' in status:
        stat = status['state']
        content = current['file']
        t = int(float(status['elapsed']))
        return content, stat, t
    else:
        return '', '', 0

class MPDStatus(View):
    def get(self, request):
        json_str = json.dumps(mpd_status())
        callback = request.GET.get('callback')
        if callback:
            json_str = "%s(%s)" % (callback, json_str)
            response = HttpResponse(
                json_str, 
                content_type='application/javascript; charset=UTF-8'
            )
        else:
            response = HttpResponse(
                json_str, 
                content_type='application/json; charset=UTF-8'
            )
        return response

class ListStation(LoginRequiredMixin, View):
    def get(self, request):
        logger = logging.getLogger('radio.debug')
        logger.debug(request)
        stations = Station.objects.all().order_by('station_no')
        d = {'stations': stations}
        return render(request, 'radiko_app/station.html', d)

    def post(self, request):
        logger = logging.getLogger('radio.debug')
        logger.debug(request)
        if request.method == 'POST':
            logger.debug(request.POST)
            station = request.POST['station_id']
            name = Station.objects.get(station_id=station).name
            if 'play' in request.POST:
                url = '{}/radiko/stream/{}'.format(settings.BASE_URL, station)
                mpd_play(url, name)
                response = HttpResponse(
                    'Playing on MPD<br><br>Live: {}'.format(name)
                )
                return response
            elif 'stream' in request.POST:
                d = {'play':{
                    'station_id': station, 
                    'name': name
                }}
                return render(request, 'radiko_app/play_live_stream.html', d)

class ListStationMPD(LoginRequiredMixin, View):
    def get(self, request):
        logger = logging.getLogger('radio.debug')
        logger.debug(request)
        stations = Station.objects.all().order_by('station_no')
        d = {'stations': stations}
        return render(request, 'radiko_app/station_mpd.html', d)

    def post(self, request):
        logger = logging.getLogger('radio.debug')
        logger.debug(request)
        if request.method == 'POST':
            logger.debug(request.POST)
            station = request.POST['station_id']
            name = Station.objects.get(station_id=station).name
            url = '{}/radiko/stream/{}'.format(settings.BASE_URL, station)
            mpd_play(url, name)
            response = HttpResponse(
                'Playing on MPD<br><br>Live: {}'.format(name)
            )
            return response

class ListStationStream(LoginRequiredMixin, View):
    def get(self, request):
        logger = logging.getLogger('radio.debug')
        logger.debug(request)
        stations = Station.objects.all().order_by('station_no')
        d = {'stations': stations}
        return render(request, 'radiko_app/station_stream.html', d)

    def post(self, request):
        logger = logging.getLogger('radio.debug')
        logger.debug(request)
        if request.method == 'POST':
            logger.debug(request.POST)
            station = request.POST['station_id']
            name = Station.objects.get(station_id=station).name
            d = {'play':{
                'station_id': station, 
                'name': name
            }}
            return render(request, 'radiko_app/play_live_stream.html', d)

class ListProgram(LoginRequiredMixin, View):

    def render_(self, request, station_id, kwargs):
        logger = logging.getLogger('radio.debug')
        logger.debug(request)
        logger.debug(station_id)
        s = Station.objects.filter(station_id=station_id)
        if s:
            name = s[0].name
        else:
            name = ''
        current = datetime.now().strftime('%Y%m%d%H%M%S')
        pgmp_ = Program.objects.filter(
            station_id=station_id
        ).filter(ft__lte=current).order_by('ft').reverse()
        pgmp = []
        for pgm in pgmp_:
            ft = datetime.strptime(pgm.ft, '%Y%m%d%H%M%S')
            pgmp.append({
                'id': pgm.id,
                'from': ft.strftime('%m/%d %H:%M'),
                'durm': '{:d}'.format(int(int(pgm.dur)/60)), 
                'title': pgm.title,
                'ft': pgm.ft,
                'to': pgm.to,
                'dur': pgm.dur,
                'download': pgm.download,
            })
        pgmf_ = Program.objects.filter(
            station_id=station_id
        ).filter(to__gt=current).order_by('ft').reverse()
        pgmf = []
        for pgm in pgmf_:
            ft = datetime.strptime(pgm.ft, '%Y%m%d%H%M%S')
            pgmf.append({
                'id': pgm.id,
                'from': ft.strftime('%m/%d %H:%M'),
                'durm': '{:d}'.format(int(int(pgm.dur)/60)), 
                'title': pgm.title,
                'ft': pgm.ft,
                'to': pgm.to,
                'dur': pgm.dur,
                'download': pgm.download,
            })
        d = {
            'station_id': station_id, 
            'name': name, 
            'programs_past': pgmp, 
            'programs_future': pgmf
        }
        if 'target' not in kwargs:
            return render(request, 'radiko_app/program.html', d)
        elif kwargs['target'] == 'mpd':
            return render(request, 'radiko_app/program_mpd.html', d)
        elif kwargs['target'] == 'stream':
            return render(request, 'radiko_app/program_stream.html', d)
        else:
            return render(request, 'radiko_app/program.html', d)

    def get(self, request, station_id, **kwargs):
        
        return self.render_(request, station_id, kwargs)

    def post(self, request, station_id, **kwargs):
        logger = logging.getLogger('radio.debug')
        logger.debug(request)
        if request.method == 'POST':
            logger.debug(request.POST)
            if 'downld' in request.POST:
                dllist = request.POST.getlist('chk_dl')
                for dl in dllist:
                    p_id = int(dl)
                    p = Program.objects.get(id=p_id)
                    logger.debug((p.title, p.ft))
                    download_program(p_id)
                    p.download = 1
                    p.save()
                response = HttpResponse('Download scheduled')
                return response

            if 'tmrec' in request.POST:
                dllist = request.POST.getlist('chk_tm')
                for dl in dllist:
                    p_id = int(dl)
                    p = Program.objects.get(id=p_id)
                    station = p.station_id
                    ft = p.ft
                    to = p.to
                    dur = p.dur
                    logger.debug((p.title, p.ft))
                    pgm_data = serializers.serialize(
                        "json", [p], ensure_ascii=False
                    )
                    params = {
                        'station_id': station, 
                        'ft': ft, 
                        'to': to, 
                        'dur': dur, 
                        'p_id': p_id, 
                        'data': pgm_data
                    }
                    rec_start = datetime.strptime(ft, '%Y%m%d%H%M%S')
                    record_program(params, schedule=rec_start)
                    p.download = 11
                    p.save()
                response = HttpResponse('Recording scheduled')
                return response

            p_id = request.POST['id']
            p = Program.objects.get(id=p_id)
            station = p.station_id
            ft = p.ft
            to = p.to
            dur = p.dur
            title = p.title
            start = datetime.strptime(ft, '%Y%m%d%H%M%S')
            t_from = start.strftime('%Y-%m-%d %H:%M')
            
            if 'seek' in request.POST:
                seek = request.POST['seek']
            else:
                seek = 0
            if 'play' in request.POST:
                url = (
                    '{0}/radiko/stream/{1}' 
                    '?ft={2}&to={3}&seek={4}'
                ).format(settings.BASE_URL, station, ft, to, seek)
                mpd_play(url, title)
                d = {'play':{
                    'id': p_id,
                    'station_id': station_id, 
                    'ft': ft, 
                    'to': to, 
                    'dur': dur, 
                    'seek': seek,
                    'title': title,
                    'from': t_from,
                    'url': url
                }}
                return render(request, 'radiko_app/play_tfree_mpd.html', d)
            elif 'stream' in request.POST:
                d = {'play':{
                    'id': p_id,
                    'station_id': station_id, 
                    'ft': ft, 

templates/radiko_app/play_live_stream.html
{% extends "base1.html" %}

{% block body %}
  {{ play.name }}<br><br>
  <audio id="audio" src="{% url 'radiko_app:tune' station_id=play.station_id %}" preload="metadata" autoplay>
  </audio>
<div>
<input type="button" value="Play" onClick="playAudio()">
<input type="button" value="Pause" onClick="pauseAudio()">
<input type="button" value="Vol.UP" onClick="upVolume()">
<input type="button" value="Vol.DN" onClick="downVolume()"><br>
Playing... <span id="position">0</span><br>
<span id="status"></span>
</div>
<script type="text/javascript">
var v = document.getElementById("audio");
playAudio();

function playAudio() {
	v.play();
	v.addEventListener("timeupdate", function(){
		document.getElementById("position").innerHTML = v.currentTime.toFixed(1);
	}, false);
}

function pauseAudio() {
	v.pause();
}

function upVolume() {
	v.volume = v.volume + 0.1;
}

function downVolume() {
	v.volume = v.volume - 0.1;
}
</script>

{% endblock %}

templates/radiko_app/play_tfree_mpd.html
{% extends "base1.html" %}

{% block body %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  Playing on MPD<br><br>
  {{ play.from }}<br>
  {{ play.title }}<br><br>
  <form name="seek" id="seek" method="post" action="">
    {% csrf_token %}
    <input type="hidden" name="id" value="{{ play.id }}">
    <input type="submit" name="play" value="Seek">
    <input type="range" id="seek-range" name="seek" value="{{ play.seek }}" step="1" min="0" max="{{ play.dur }}"/>
    <span id="value">{{ play.seek }}</span>
  </form>
<br>
Position(sec): <span id="position">0</span> / <span id="duration">{{ play.dur }}</span><br>
<script type="text/javascript">
  var elem = document.getElementById('seek-range');
  var target = document.getElementById('value');
  var rangeValue = function (elem, target) {
    return function(evt){
      target.innerHTML = elem.value;
    }
  }
  elem.addEventListener('input', rangeValue(elem, target));
  $(function() {
    update();
    check = setInterval("update()",1000);
  });
  function update(){
    $.ajax({
      url: '{% url 'radiko_app:status' %}',
      type: 'GET',
      dataType: 'json',
      cache : false
    })
    .done(function(res) {
       if(res[0] == "{{play.url | safe}}"){
        let t = Number({{ play.seek }}) + res[2];
        document.getElementById("position").innerHTML = t;
      } else {
        clearInterval(check);
      }
    });
  }
</script>
{% endblock %}

templates/radiko_app/play_tfree_stream.html
{% extends "base1.html" %}

{% block body %}
  {{ play.from }}<br>
  {{ play.title }}<br><br>
  <form name="seek" id="seek" method="post" action="">
    {% csrf_token %}
    <input type="hidden" name="id" value="{{ play.id }}">
    <input type="hidden" name="station_id" value="{{ play.station_id }}">
    <input type="hidden" name="ft" value="{{ play.ft }}">
    <input type="hidden" name="to" value="{{ play.to }}">
    <input type="hidden" name="dur" value="{{ play.dur }}">
    <input type="hidden" name="title" value="{{ play.title }}">
    <input type="hidden" name="from" value="{{ play.from }}">
    <input type="submit" name="stream" value="Seek">
    <input type="range" id="seek-range" name="seek" value="{{ play.seek }}" step="1" min="0" max="{{ play.dur }}"/>
      <span id="value">{{ play.seek }}</span>
  <script>
    var elem = document.getElementById('seek-range');
    var target = document.getElementById('value');
    var rangeValue = function (elem, target) {
      return function(evt){
        target.innerHTML = elem.value;
      }
    }
    elem.addEventListener('input', rangeValue(elem, target));
  </script>
  </form>
  <br>
  <audio id="audio" src="{% url 'radiko_app:tune' station_id=play.station_id %}?ft={{ play.ft }}&to={{ play.to }}&seek={{ play.seek }}" preload="metadata" autoplay>
  </audio>
<div>
<input type="button" value="Play" onClick="playAudio()">
<input type="button" value="Pause" onClick="pauseAudio()">
<input type="button" value="Vol.UP" onClick="upVolume()">
<input type="button" value="Vol.DN" onClick="downVolume()"><br>
Current Pos.(sec)：<span id="position">0</span><br>
Total Length（sec）：<span id="duration">{{ play.dur }}</span><br>
<span id="status"></span>
</div>
<script type="text/javascript">
var v = document.getElementById("audio");
playAudio();

function playAudio() {
	v.play();
	v.addEventListener("timeupdate", function(){
		document.getElementById("position").innerHTML = (Number({{ play.seek }}) + v.currentTime).toFixed(1);
	}, false);
}

function pauseAudio() {
	v.pause();
}

function upVolume() {
	v.volume = v.volume + 0.1;
}

function downVolume() {
	v.volume = v.volume - 0.1;
}
</script>

{% endblock %}

templates/radiko_app/program.html
{% extends "base.html" %}

{% block title %}Time Table {{ name }}{% endblock %}

{% block content %}
  <form id="timer-record" name="timerrec" method="post" action="" target="if-downld">
    {% csrf_token %}
    <input type="hidden" name="station_id" value="{{ station_id }}">
  </form>
  <form id="bulk-download" name="download" method="post" action="" target="if-downld">
    {% csrf_token %}
    <input type="hidden" name="station_id" value="{{ station_id }}">
  </form>

  {{ name }}
  <a href="#now">Jump to now</a>
    <table border="1" style="table-layout:fixed; width:640px;">
      <thead>
        <tr>
          <th style="width:80px;">Start</th>
          <th style="width:30px;">DUR</th>
          <th style="width:300px;">Title</th>
          <th style="width:90px;">
            <input type="submit" name="tmrec" value="Rec" form="timer-record">
            <!--
            <input type="submit" name="tmcancel" value="Cncl" form="timer-record">
            -->
          </th>
        </tr>
      </thead>
      <tbody>
        {% for prog in programs_future %}
          <tr>
            <td>{{ prog.from }}</td>
            <td align="right">{{ prog.durm }}</td>
            <td>{{ prog.title }}</td>
            <td align="center">
            <span style="display:block; text-align:left; width:50px">
              <input type="checkbox" name="chk_tm" value="{{ prog.id }}" form="timer-record">
              {{ prog.download }}
            </span>
            </td>
          </tr>
        {% endfor %}
        <tr>
          <th>Start</th>
          <th>DUR</th>
          <th>Title</th>
          <th>
            <input type="submit" name="tmrec" value="Rec" form="timer-record">
            <!--
            <input type="submit" name="tmcancel" value="Cncl" form="timer-record">
            -->
          </th>
        </tr>
        <tr>
          <td colspan=4>
            <a name="now">{{ name }}</a>
          </td>
        </tr>
        <tr>
          <td colspan=3 align="center">
            <IFRAME NAME="if-control" id="control" width="500" height="180"></IFRAME>
          </td>
          <td align="center">
            <IFRAME NAME="if-downld" id="if-downld" width="100" height="180"></IFRAME>
          </td>
        </tr>
        <tr>
          <td colspan=4>
            <a name="now">{{ name }}</a>
          </td>
        </tr>
        <tr>
          <th>Start</th>
          <th>DUR</th>
          <th>Title</th>
          <th>
            <input type="submit" name="downld" value="Download" form="bulk-download">
          </th>
        </tr>
        {% for prog in programs_past %}
          <tr>
            <td>{{ prog.from }}</td>
            <td align="right">{{ prog.durm }}</td>
            <td>{{ prog.title }}</td>
            <td align="left">
            <form name="f1" id="f1" method="post" action="" target="if-control">
              {% csrf_token %}
              <input type="hidden" name="id" value="{{ prog.id }}">
              <input type="submit" name="play" value="M">
              <input type="submit" name="stream" value="S">
              <input type="checkbox" name="chk_dl" value="{{ prog.id }}" form="bulk-download">
              {{ prog.download }}
            </form>
            </td>
          </tr>
        {% endfor %}
        <tr>
          <th>Start</th>
          <th>DUR</th>
          <th>Title</th>
          <th>
            <input type="submit" name="downld" value="Download" form="bulk-download">
          </th>
        </tr>
      </tbody>
    </table>
    {{ name }}
    <a href="#now">Jump to now</a><br>
  <br>
{% endblock %}

templates/radiko_app/program_mpd.html
{% extends "base.html" %}

{% block title %}Time Table {{ name }}{% endblock %}

{% block content %}
  <form id="timer-record" name="timerrec" method="post" action="" target="if-downld">
    {% csrf_token %}
    <input type="hidden" name="station_id" value="{{ station_id }}">
  </form>
  <form id="bulk-download" name="download" method="post" action="" target="if-downld">
    {% csrf_token %}
    <input type="hidden" name="station_id" value="{{ station_id }}">
  </form>

  {{ name }}
  <a href="#now">Jump to now</a>
    <table border="1" style="table-layout:fixed; width:640px;">
      <thead>
        <tr>
          <th style="width:80px;">Start</th>
          <th style="width:30px;">DUR</th>
          <th style="width:300px;">Title</th>
          <th style="width:90px;">
            <input type="submit" name="tmrec" value="Rec" form="timer-record">
            <!--
            <input type="submit" name="tmcancel" value="Cncl" form="timer-record">
            -->
          </th>
        </tr>
      </thead>
      <tbody>
        {% for prog in programs_future %}
          <tr>
            <td>{{ prog.from }}</td>
            <td align="right">{{ prog.durm }}</td>
            <td>{{ prog.title }}</td>
            <td align="center">
            <span style="display:block; text-align:left; width:50px">
              <input type="checkbox" name="chk_tm" value="{{ prog.id }}" form="timer-record">
              {{ prog.download }}
            </span>
            </td>
          </tr>
        {% endfor %}
        <tr>
          <th>Start</th>
          <th>DUR</th>
          <th>Title</th>
          <th>
            <input type="submit" name="tmrec" value="Rec" form="timer-record">
            <!--
            <input type="submit" name="tmcancel" value="Cncl" form="timer-record">
            -->
          </th>
        </tr>
        <tr>
          <td colspan=4>
            <a name="now">{{ name }}</a>
          </td>
        </tr>
        <tr>
          <td colspan=3 align="center">
            <IFRAME NAME="if-control" id="control" width="500" height="180"></IFRAME>
          </td>
          <td align="center">
            <IFRAME NAME="if-downld" id="if-downld" width="100" height="180"></IFRAME>
          </td>
        </tr>
        <tr>
          <td colspan=4>
            <a name="now">{{ name }}</a>
          </td>
        </tr>
        <tr>
          <th>Start</th>
          <th>DUR</th>
          <th>Title</th>
          <th>
            <input type="submit" name="downld" value="Download" form="bulk-download">
          </th>
        </tr>
        {% for prog in programs_past %}
          <tr>
            <td>{{ prog.from }}</td>
            <td align="right">{{ prog.durm }}</td>
            <td>{{ prog.title }}</td>
            <td align="left">
            <form name="f1" id="f1" method="post" action="" target="if-control">
              {% csrf_token %}
              <input type="hidden" name="id" value="{{ prog.id }}">
              <input type="submit" name="play" value="Play">
              <input type="checkbox" name="chk_dl" value="{{ prog.id }}" form="bulk-download">
              {{ prog.download }}
            </form>
            </td>
          </tr>
        {% endfor %}
        <tr>
          <th>Start</th>
          <th>DUR</th>
          <th>Title</th>
          <th>
            <input type="submit" name="downld" value="Download" form="bulk-download">
          </th>
        </tr>
      </tbody>
    </table>
    {{ name }}
    <a href="#now">Jump to now</a><br>
  <br>
{% endblock %}

templates/radiko_app/program_stream.html
{% extends "base.html" %}

{% block title %}Time Table {{ name }}{% endblock %}

{% block content %}
  <form id="timer-record" name="timerrec" method="post" action="" target="if-downld">
    {% csrf_token %}
    <input type="hidden" name="station_id" value="{{ station_id }}">
  </form>
  <form id="bulk-download" name="download" method="post" action="" target="if-downld">
    {% csrf_token %}
    <input type="hidden" name="station_id" value="{{ station_id }}">
  </form>

  {{ name }}
  <a href="#now">Jump to now</a>
    <table border="1" style="table-layout:fixed; width:640px;">
      <thead>
        <tr>
          <th style="width:80px;">Start</th>
          <th style="width:30px;">DUR</th>
          <th style="width:300px;">Title</th>
          <th style="width:90px;">
            <input type="submit" name="tmrec" value="Rec" form="timer-record">
            <!--
            <input type="submit" name="tmcancel" value="Cncl" form="timer-record">
            -->
          </th>
        </tr>
      </thead>
      <tbody>
        {% for prog in programs_future %}
          <tr>
            <td>{{ prog.from }}</td>
            <td align="right">{{ prog.durm }}</td>
            <td>{{ prog.title }}</td>
            <td align="center">
            <span style="display:block; text-align:left; width:50px">
              <input type="checkbox" name="chk_tm" value="{{ prog.id }}" form="timer-record">
              {{ prog.download }}
            </span>
            </td>
          </tr>
        {% endfor %}
        <tr>
          <th>Start</th>
          <th>DUR</th>
          <th>Title</th>
          <th>
            <input type="submit" name="tmrec" value="Rec" form="timer-record">
            <!--
            <input type="submit" name="tmcancel" value="Cncl" form="timer-record">
            -->
          </th>
        </tr>
        <tr>
          <td colspan=4>
            <a name="now">{{ name }}</a>
          </td>
        </tr>
        <tr>
          <td colspan=3 align="center">
            <IFRAME NAME="if-control" id="control" width="500" height="180"></IFRAME>
          </td>
          <td align="center">
            <IFRAME NAME="if-downld" id="if-downld" width="100" height="180"></IFRAME>
          </td>
        </tr>
        <tr>
          <td colspan=4>
            <a name="now">{{ name }}</a>
          </td>
        </tr>
        <tr>
          <th>Start</th>
          <th>DUR</th>
          <th>Title</th>
          <th>
            <input type="submit" name="downld" value="Download" form="bulk-download">
          </th>
        </tr>
        {% for prog in programs_past %}
          <tr>
            <td>{{ prog.from }}</td>
            <td align="right">{{ prog.durm }}</td>
            <td>{{ prog.title }}</td>
            <td align="left">
            <form name="f1" id="f1" method="post" action="" target="if-control">
              {% csrf_token %}
              <input type="hidden" name="id" value="{{ prog.id }}">
              <input type="submit" name="stream" value="Play">
              <input type="checkbox" name="chk_dl" value="{{ prog.id }}" form="bulk-download">
              {{ prog.download }}
            </form>
            </td>
          </tr>
        {% endfor %}
        <tr>
          <th>Start</th>
          <th>DUR</th>
          <th>Title</th>
          <th>
            <input type="submit" name="downld" value="Download" form="bulk-download">
          </th>
        </tr>
      </tbody>
    </table>
    {{ name }}
    <a href="#now">Jump to now</a><br>
  <br>
{% endblock %}

templates/radiko_app/station.html
{% extends "base.html" %}

{% block title %}Station List{% endblock %}

{% block content %}
  
    <table border="1" style="table-layout:fixed; width:560px;">
      <thead>
        <tr>
          <th style="width:20px;">No</th>
          <th style="width:70px;">Region</th>
          <th style="width:70px;">Area</th>
          <th style="width:120px;">Station</th>
          <th style="width:80px;">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for station in stations %}
          <tr>
            <td>{{ station.station_no }}</td>
            <td>{{ station.region }}</td>
            <td>{{ station.area_name }}</td>
            <td><a href="/radiko/program/{{ station.station_id }}#now">{{ station.name }}</a></td>
            <td align="center">
            <form name="f1" id="f1" method="post" action="" target="control">
            {% csrf_token %}
            <input type="hidden" name="station_id" value="{{ station.station_id }}">
            <input type="submit" name="play" value="MPD">
            <input type="submit" name="stream" value="Stream">
            </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  <IFRAME NAME="control" id="control" width="560" height="200"></IFRAME>
{% endblock %}

templates/radiko_app/station_mpd.html
{% extends "base.html" %}

{% block title %}Station List{% endblock %}

{% block content %}
  
    <table border="1" style="table-layout:fixed; width:560px;">
      <thead>
        <tr>
          <th style="width:20px;">No</th>
          <th style="width:70px;">Region</th>
          <th style="width:70px;">Area</th>
          <th style="width:120px;">Station</th>
          <th style="width:80px;">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for station in stations %}
          <tr>
            <td>{{ station.station_no }}</td>
            <td>{{ station.region }}</td>
            <td>{{ station.area_name }}</td>
            <td><a href="/radiko/mpd/program/{{ station.station_id }}#now">{{ station.name }}</a></td>
            <td align="center">
            <form name="f1" id="f1" method="post" action="" target="control">
            {% csrf_token %}
            <input type="hidden" name="station_id" value="{{ station.station_id }}">
            <input type="submit" name="play" value="Play">
            </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  <IFRAME NAME="control" id="control" width="560" height="200"></IFRAME>
{% endblock %}

templates/radiko_app/station_stream.html
{% extends "base.html" %}

{% block title %}Station List{% endblock %}

{% block content %}
  
    <table border="1" style="table-layout:fixed; width:560px;">
      <thead>
        <tr>
          <th style="width:20px;">No</th>
          <th style="width:70px;">Region</th>
          <th style="width:70px;">Area</th>
          <th style="width:120px;">Station</th>
          <th style="width:80px;">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for station in stations %}
          <tr>
            <td>{{ station.station_no }}</td>
            <td>{{ station.region }}</td>
            <td>{{ station.area_name }}</td>
            <td><a href="/radiko/stream/program/{{ station.station_id }}#now">{{ station.name }}</a></td>
            <td align="center">
            <form name="f1" id="f1" method="post" action="" target="control">
            {% csrf_token %}
            <input type="hidden" name="station_id" value="{{ station.station_id }}">
            <input type="submit" name="stream" value="Play">
            </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  <IFRAME NAME="control" id="control" width="560" height="200"></IFRAME>
{% endblock %}